#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake $targetType Utilities/rectificationCompositionBCs   # must precede main solver (linked by it)

wmake $targetType

wmake $targetType fvModels/VoFTurbulenceDamping
wmake $targetType fvModels/VoFCavitation

wmake $targetType Utilities/adjustContinuity
wmake $targetType Utilities/gasMeanVelocityForce
wmake $targetType Utilities/incompressibleVoFCyclic
wmake $targetType Utilities/setHoldup
wmake $targetType Utilities/prghNonConformalCyclicPressureFvPatchScalarField
wmake $targetType Utilities/setComposition
wmake $targetType Utilities/totalRefluxPatchGasMeanVelocityForce
wmake $targetType Utilities/reservoirFenske
#------------------------------------------------------------------------------
