#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean

wclean libso fvModels/VoFTurbulenceDamping
wclean libso fvModels/VoFCavitation


wclean libso Utilities/adjustContinuity
wclean libso Utilities/gasMeanVelocityForce
wclean libso Utilities/incompressibleVoFCyclic
wclean libso Utilities/setHoldup
wclean libso Utilities/prghNonConformalCyclicPressureFvPatchScalarField
wclean libso Utilities/setComposition
wclean libso Utilities/rectificationCompositionBCs
wclean libso Utilities/totalRefluxPatchGasMeanVelocityForce
wclean libso Utilities/reservoirFenske
#------------------------------------------------------------------------------
